In [3]:
import numpy as np

arr = np.array([
    [6, -8, 73, -110],
    [np.nan, -8, 0, 94]
])

print(arr)
#replace NaN with 0

arr_no_nan = np.nan_to_num(arr, nan=0)

print(arr_no_nan)

#interchange row and column
result = arr_no_nan.T

print(result)



[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [6]:
import numpy as np

arr = np.arange(24).reshape(2,3,4)

print(arr.shape)

new_arr = np.moveaxis(arr, [0,1,2], [1,2,0])

print(new_arr.shape)

new_arr = np.moveaxis(arr, 0, -1)

print(new_arr.shape)


(2, 3, 4)
(4, 2, 3)
(3, 4, 2)


In [9]:
import numpy as np

arr = np.array([
    [10, np.nan, 30],
    [20, 40, np.nan],
    [30, 50, 60]
])

print(arr)
#calculate column means
col_mean = np.nanmean(arr, axis=0)

print(col_mean)

#Replace NaN with column mean
inds = np.where(np.isnan(arr))

arr[inds] = np.take(col_mean, inds[1])

print(arr)



[[10. nan 30.]
 [20. 40. nan]
 [30. 50. 60.]]
[20. 45. 45.]
[[10. 45. 30.]
 [20. 40. 45.]
 [30. 50. 60.]]


In [ ]:
import numpy as np
 #Replace negative values with zero
arr = np.array([5, -2, 8, -7, 4, -1])

print(arr)

#m3thod 2
arr[arr < 0] = 0

print(arr)
#method 2

arr = np.array([5,-2,8,-7,4,-1])

result = np.where(arr < 0, 0, arr)

print(result)

[ 5 -2  8 -7  4 -1]
[5 0 8 0 4 0]
[5 0 8 0 4 0]
