In [1]:
import numpy as np

In [2]:
# > convert 1d array to 2d

arr = np.array([1,2,3])
print(arr.shape)
arr1 = arr.reshape(1,3)
print(arr)
print (arr1)

(3,)
[1 2 3]
[[1 2 3]]


In [3]:
# > print array attributes (like shape m dimnesion, data type, itemsize)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)
print (arr)

(3,)
1
int64
8
[1 2 3]


In [4]:
#>Create 3x3 array of all 9s
arr2 = np.full((3,3),9)
print("\n3x3 array of 9s:")
print(arr2)


3x3 array of 9s:
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [7]:
# > create a 1d array of 10 evnely spaced values betwnne 25 and 125
arr3 = np.linspace(25,125,10)
print(arr3)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [8]:
# > conver a python list into a numpy array
list = [1,2,3,4,5]
arr = np.array(list)
print(arr)


[1 2 3 4 5]


In [9]:
# > reversre a 1d numpy array
revarr = arr[::-1]
print(revarr)

[5 4 3 2 1]


In [10]:

# > Create a 4×4×3 array and extract value at its second set, first row and last column
arr4 = np.arange(48).reshape(4,4,3)
print(arr4)
print(arr4[1,0,-1])


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
14


In [11]:

# > Create a 4×4 and Extract Odd Rows and Even Columns 
arr5 = np.arange(1,17).reshape(4,4)
print("\n4x4 Array:")
print(arr5)
print(arr5[0::2,1::2])


4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  4]
 [10 12]]


In [12]:
# slice the first two rows and first two columns of second set from a 4*4*3 array
arr6 = arr4[1,0:2,0:2]
print(arr6)

[[12 13]
 [15 16]]


In [16]:
# replace all odd numbers in a numpy array with -1 by itterating usign for loop [[23,56,78,93], [71,82,13,24]]
arr7 = np.array([[23,56,78,93],[71,82,13,24]])
print(arr7)
for i in range (arr7.shape[0]):
    for j in range(arr7.shape[1]):
     if arr7[i, j] % 2 != 0:
      arr7[i, j] = -1
print(arr7)

[[23 56 78 93]
 [71 82 13 24]]
[[-1 56 78 -1]
 [-1 82 -1 24]]


In [18]:
# > get the indices of non-zero elements in an array [1,0,2,0,3,0,4]
arr8 = np.array([1,0,2,0,3,0,4])
indices = np.nonzero(arr8)
print(indices)

(array([0, 2, 4, 6]),)


In [19]:
#> perform arithemetic operations on two numpy arrays element-wise
#add two numpy arrays element by element
# multyply two numpy arrays element by element

arra = np.array([1,2,3,4,5])
arrb = np.array([11,12,13,14,15])
arradd = arra+arrb
arrmul = arra*arrb
print(arra)
print(arrb)
print(arradd)
print(arrmul)

[1 2 3 4 5]
[11 12 13 14 15]
[12 14 16 18 20]
[11 24 39 56 75]


In [20]:
# > write a code to compute the dot product of two  numpy arrays arr1 = [15,20,25] arr2 = [ 10,40,37]
arr9 = np.array ([15,20,25])
arr10 = np.array([10,40,37])
arrdot = np.dot(arr9,arr10)
print(arrdot)

1875
