In [2]:
import numpy as np
arr = np.array([[1,2,3,4],
               [4,5,6,7]])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(np.zeros(arr.shape))
print(np.ones(arr.shape))
print(np.full((2,3),7))
print(np.eye(3))
print(np.arange(1,10,2))

print(np.linspace(0, 1, 5))

[[1 2 3 4]
 [4 5 6 7]]
<class 'numpy.ndarray'>
(2, 4)
2
8
int64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
